-- portable .port schema, version 1.
--
-- @schema_version 1
-- @name initial
--
-- Conventions, enforced by lint and by tests:
--
--   * Money, quantity, price, and rate columns are TEXT holding the canonical
--     decimal form, and carry a `-- decimal` marker. There is no REAL, FLOAT,
--     DOUBLE, or NUMERIC column anywhere in this file, and the no-float lint
--     rule fails the build if one appears. NUMERIC is on that list because
--     SQLite's NUMERIC affinity silently stores as REAL whatever it cannot
--     hold as an integer -- ADR 0005.
--   * Dates are TEXT `YYYY-MM-DD`. Timestamps are TEXT ISO-8601 UTC with a
--     trailing `Z`. Accounting uses dates; timestamps appear only where a time
--     genuinely matters (a price's as-of, a ledger row's created_at).
--   * Booleans are INTEGER CHECK (x IN (0, 1)).
--   * Every table and column comment here is the source for docs/schema.md,
--     generated by `make docs`, so it cannot drift.
--
-- Table classes (ADR 0010) -- this partition drives `pt rebuild`:
--
--   LEDGER     "transaction". Append-only, enforced by trigger.
--   REFERENCE  instrument*, price, corporate_action. Facts about the world.
--   CONFIG     account, tax_rate_schedule, benchmark*, return_policy, ...
--              Effective-dated, immutable once effective.
--   DERIVED    position*, lot*, cash_balance, valuation_snapshot*, ...
--              Dropped and rebuilt by replay.

-- No PRAGMA statements here. Connection configuration -- foreign_keys,
-- journal_mode, synchronous -- lives in persistence/connection.py, which
-- ADR 0002 makes its single home. A PRAGMA inside a migration would also
-- be a silent no-op, because migrations run inside a transaction.

-- =============================================================================
-- META
-- =============================================================================

-- @table schema_migration
-- Applied migrations, one row each. Mirrors fafnir's `meta.schema_migration`
-- so that anyone who has read that warehouse recognises this one.
CREATE TABLE IF NOT EXISTS schema_migration (
    -- Monotonic migration number. Never reused, never renumbered.
    version     INTEGER PRIMARY KEY,
    -- Short slug from the migration filename.
    name        TEXT NOT NULL,
    -- SHA-256 of the up-migration text as applied. A mismatch on open means
    -- the file changed after being applied, which is a corruption of the
    -- audit trail, not a routine edit.
    checksum    TEXT NOT NULL,
    -- ISO-8601 UTC.
    applied_at  TEXT NOT NULL,
    -- The portable version that applied it.
    applied_by  TEXT NOT NULL
);

-- @table meta
-- Portfolio-level metadata as key/value, so that adding a property is not a
-- migration. The keys `schema_version`, `portfolio_name`, `inception_date`,
-- `base_currency`, `fiscal_year_end`, `created_at`, `updated_at`, and
-- `portable_version` are required and are validated by `pt validate`.
CREATE TABLE IF NOT EXISTS meta (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL
);

-- @table meta_change_log
-- Redefinitions and name changes, with their dates and reasons
-- (PORT-GIPS-I17: "Redefinition of the reporting entity or composite, and name
-- changes -- date and description"). Append-only by convention and by
-- `pt validate`; the ledger's trigger discipline is reserved for transactions.
CREATE TABLE IF NOT EXISTS meta_change_log (
    change_id   INTEGER PRIMARY KEY,
    key         TEXT NOT NULL,
    old_value   TEXT,
    new_value   TEXT NOT NULL,
    -- The date the change takes effect, not the date it was entered.
    effective_from TEXT NOT NULL,
    reason      TEXT NOT NULL,
    created_at  TEXT NOT NULL
);

-- =============================================================================
-- REFERENCE
-- =============================================================================

-- @table instrument
-- The security master, local to this file, hydrated from a provider and
-- cached. A base row per instrument; options and bonds carry a detail row in
-- `instrument_option` / `instrument_bond` (ADR 0004 -- detail tables rather
-- than a JSON column, so that NOT NULL and CHECK actually bind).
CREATE TABLE IF NOT EXISTS instrument (
    instrument_id   INTEGER PRIMARY KEY,
    -- The instrument's current symbol. NOT an identifier: symbols are reused
    -- and reassigned. Resolution at a date goes through
    -- `instrument_symbol_history`.
    symbol          TEXT NOT NULL,
    instrument_type TEXT NOT NULL
        CHECK (instrument_type IN (
            'equity', 'etf', 'mutual_fund', 'adr', 'cash', 'money_market',
            'option', 'bond'
        )),
    name            TEXT,
    -- ISO 4217. USD only in v0.1, but carried on every row so that
    -- multi-currency is an extension rather than a migration (bootstrap §4.1).
    currency        TEXT NOT NULL DEFAULT 'USD',
    exchange        TEXT,
    cusip           TEXT,
    isin            TEXT,
    figi            TEXT,
    sector          TEXT,
    industry        TEXT,
    asset_class     TEXT,
    country         TEXT,
    is_active       INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    -- Where this row came from: 'manual', 'provider:<name>', 'import'.
    source          TEXT NOT NULL DEFAULT 'manual',
    -- The provider's own key for this instrument, so a hydration can be traced
    -- back to the row that produced it (PORT-GIPS-J03).
    provider_ref    TEXT,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL,
    UNIQUE (symbol, instrument_type)
);

CREATE INDEX IF NOT EXISTS ix_instrument_symbol ON instrument (symbol);
CREATE INDEX IF NOT EXISTS ix_instrument_cusip ON instrument (cusip) WHERE cusip IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_instrument_isin ON instrument (isin) WHERE isin IS NOT NULL;

-- @table instrument_symbol_history
-- Ticker history, so a symbol resolves to the instrument it named *on the
-- trade date* rather than the one it names today. Mirrors fafnir's
-- `core.symbol_xref`. A rename or a relist silently rewrites history without
-- this.
CREATE TABLE IF NOT EXISTS instrument_symbol_history (
    instrument_id   INTEGER NOT NULL REFERENCES instrument (instrument_id),
    symbol          TEXT NOT NULL,
    valid_from      TEXT NOT NULL DEFAULT '1900-01-01',
    -- NULL means currently valid.
    valid_to        TEXT,
    is_primary      INTEGER NOT NULL DEFAULT 1 CHECK (is_primary IN (0, 1)),
    source          TEXT NOT NULL DEFAULT 'manual',
    PRIMARY KEY (instrument_id, symbol, valid_from)
);

CREATE INDEX IF NOT EXISTS ix_symbol_history_lookup
    ON instrument_symbol_history (symbol, valid_from);

-- @table instrument_option
-- Listed option detail. One row per option instrument.
CREATE TABLE IF NOT EXISTS instrument_option (
    instrument_id   INTEGER PRIMARY KEY REFERENCES instrument (instrument_id),
    underlier_instrument_id INTEGER NOT NULL REFERENCES instrument (instrument_id),
    -- Named `option_right` rather than `right`, which SQLite treats as a join
    -- keyword.
    option_right    TEXT NOT NULL CHECK (option_right IN ('call', 'put')),
    strike          TEXT NOT NULL,  -- decimal
    expiry          TEXT NOT NULL,
    -- Shares per contract. NOT NULL with no default, deliberately: it is 100
    -- until the day it is not (adjusted contracts after a split), and a
    -- defaulted multiplier is a 100x wrong number (ADR 0004).
    multiplier      TEXT NOT NULL,  -- decimal
    occ_symbol      TEXT,
    exercise_style  TEXT NOT NULL DEFAULT 'american'
        CHECK (exercise_style IN ('american', 'european')),
    -- Physical delivery into the underlier, or cash settlement.
    settlement      TEXT NOT NULL DEFAULT 'physical'
        CHECK (settlement IN ('physical', 'cash'))
);

CREATE INDEX IF NOT EXISTS ix_option_underlier
    ON instrument_option (underlier_instrument_id, expiry);

-- @table instrument_bond
-- Fixed income detail. One row per bond instrument.
CREATE TABLE IF NOT EXISTS instrument_bond (
    instrument_id     INTEGER PRIMARY KEY REFERENCES instrument (instrument_id),
    issuer            TEXT NOT NULL,
    -- Annual coupon rate as a decimal fraction: 4.25% is '0.0425'.
    coupon_rate       TEXT NOT NULL,  -- decimal
    -- Coupon payments per year. 0 for a zero-coupon bond.
    coupon_frequency  INTEGER NOT NULL CHECK (coupon_frequency IN (0, 1, 2, 4, 12)),
    maturity_date     TEXT NOT NULL,
    -- Day-count convention for accrued interest. Getting this wrong misstates
    -- accrued interest, which is part of market value (PORT-GIPS-A06).
    day_count         TEXT NOT NULL
        CHECK (day_count IN ('30/360', 'ACT/ACT', 'ACT/365', 'ACT/360')),
    face_value        TEXT NOT NULL,  -- decimal
    first_coupon_date TEXT,
    -- Whether prices are quoted per 100 of face ('percent_of_par') or as a
    -- money amount per bond ('price_per_bond').
    quote_basis       TEXT NOT NULL DEFAULT 'percent_of_par'
        CHECK (quote_basis IN ('percent_of_par', 'price_per_bond')),
    is_callable       INTEGER NOT NULL DEFAULT 0 CHECK (is_callable IN (0, 1)),
    next_call_date    TEXT,
    next_call_price   TEXT   -- decimal
);

-- @table price
-- The price cache. Every price records where it came from, when it was true,
-- how it was determined, and whether it is an estimate. This is not
-- convenience: PORT-GIPS-J03 requires supporting data for every reported
-- figure, including records obtained from third parties, and it is what makes
-- a return traceable to the ticks that produced it.
--
-- Prices are UNADJUSTED (PORT-GIPS-A01). Adjusted prices are not fair values
-- on the measurement date and would double-count splits.
CREATE TABLE IF NOT EXISTS price (
    price_id        INTEGER PRIMARY KEY,
    instrument_id   INTEGER NOT NULL REFERENCES instrument (instrument_id),
    price_date      TEXT NOT NULL,
    price           TEXT NOT NULL,  -- decimal
    currency        TEXT NOT NULL DEFAULT 'USD',
    -- 'manual', 'file:<path>', 'fafnir:core.daily_price', ...
    source          TEXT NOT NULL,
    -- When the source asserted this price. ISO-8601 UTC.
    as_of           TEXT NOT NULL,
    -- The GIPS fair-value hierarchy, PORT-GIPS-A02 / Firms 2.B.6:
    --   1 unadjusted quoted prices for identical investments, active markets
    --   2 observable quoted prices for similar investments, active markets
    --   3 quoted prices for identical or similar, non-active markets
    --   4 observable market-based inputs other than quoted prices
    --   5 subjective, unobservable inputs
    -- Provider EOD closes are 1. A price set by hand with no documented basis
    -- is 5, so that it shows up in the level-5 percentage (PORT-GIPS-H05)
    -- rather than hiding among the observable ones.
    valuation_level INTEGER NOT NULL CHECK (valuation_level BETWEEN 1 AND 5),
    -- How the number was arrived at, alongside the hierarchy level.
    valuation_basis TEXT NOT NULL
        CHECK (valuation_basis IN ('exchange_close', 'model', 'estimate', 'manual')),
    -- Preliminary or estimated values must be flagged, and when the final
    -- value arrives the affected snapshots must be rebuilt (PORT-GIPS-A09).
    is_estimate     INTEGER NOT NULL DEFAULT 0 CHECK (is_estimate IN (0, 1)),
    -- The provider's own row key, e.g. 'security_id=42;trade_date=2026-03-31;
    -- ingestion_run_id=91'. Lineage, per PORT-GIPS-J03.
    provider_ref    TEXT,
    created_at      TEXT NOT NULL,
    UNIQUE (instrument_id, price_date, source)
);

CREATE INDEX IF NOT EXISTS ix_price_instrument_date ON price (instrument_id, price_date);
CREATE INDEX IF NOT EXISTS ix_price_date ON price (price_date);

-- @table corporate_action
-- Corporate actions as reported by a provider. This is the *reference* record
-- of what the world did. Applying it to the portfolio produces one or more
-- ledger transactions -- the action itself never changes derived state
-- directly, so that `pt rebuild` reproduces its effect from the ledger.
CREATE TABLE IF NOT EXISTS corporate_action (
    corporate_action_id INTEGER PRIMARY KEY,
    instrument_id   INTEGER NOT NULL REFERENCES instrument (instrument_id),
    action_type     TEXT NOT NULL
        CHECK (action_type IN (
            'split', 'reverse_split', 'stock_dividend', 'cash_dividend',
            'spinoff', 'merger', 'symbol_change', 'delist', 'return_of_capital'
        )),
    -- Entitlement is determined on the ex-date; cash arrives on the pay date.
    -- Both are recorded because accruing on the wrong one shifts return across
    -- a period boundary (PORT-GIPS-A06).
    ex_date         TEXT NOT NULL,
    record_date     TEXT,
    pay_date        TEXT,
    declared_date   TEXT,
    -- 2-for-1 is numerator 2, denominator 1.
    split_numerator TEXT,   -- decimal
    split_denominator TEXT, -- decimal
    cash_amount     TEXT,   -- decimal
    -- For spinoffs and mergers: the instrument received.
    target_instrument_id INTEGER REFERENCES instrument (instrument_id),
    -- Shares of target per share held.
    target_ratio    TEXT,   -- decimal
    -- Relative fair market values used to allocate basis in a spinoff. Stored
    -- because the allocation is only defensible if the inputs are recorded.
    parent_fmv      TEXT,   -- decimal
    target_fmv      TEXT,   -- decimal
    new_symbol      TEXT,
    source          TEXT NOT NULL DEFAULT 'manual',
    provider_ref    TEXT,
    -- Whether this action has been applied to the ledger.
    applied_txn_id  INTEGER,
    created_at      TEXT NOT NULL,
    UNIQUE (instrument_id, action_type, ex_date)
);

CREATE INDEX IF NOT EXISTS ix_ca_instrument_date ON corporate_action (instrument_id, ex_date);

-- =============================================================================
-- CONFIG
-- =============================================================================

-- @table account
-- Accounts hold positions and cash. All transactions happen at account level.
CREATE TABLE IF NOT EXISTS account (
    account_id      INTEGER PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    -- Tax treatment is a first-class attribute, not a tag: it changes what a
    -- realized gain means.
    account_type    TEXT NOT NULL
        CHECK (account_type IN ('taxable', 'tax_deferred', 'tax_exempt')),
    custodian       TEXT,
    -- An alias, never the real account number.
    account_alias   TEXT,
    opened_date     TEXT NOT NULL,
    closed_date     TEXT,
    status          TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    -- PORT-GIPS-A07 / Firms 2.A.11: returns from cash must be included in all
    -- return calculations. Asset Owners 22.B.9-.10 carve out operating cash
    -- not fully available for investment. Defaulting to 'invested' means cash
    -- drag is always in the return unless somebody explicitly says otherwise;
    -- there is no implicit ex-cash basis.
    cash_treatment  TEXT NOT NULL DEFAULT 'invested'
        CHECK (cash_treatment IN ('invested', 'operating')),
    -- Default lot relief method, overridable per closing trade.
    default_relief_method TEXT NOT NULL DEFAULT 'spec'
        CHECK (default_relief_method IN ('spec', 'fifo', 'lifo', 'hifo', 'lofo', 'avg')),
    -- Whether this account can hold fractional shares. A corporate action that
    -- would create one where it cannot is an error, not a rounding.
    allows_fractional INTEGER NOT NULL DEFAULT 0 CHECK (allows_fractional IN (0, 1)),
    sweep_instrument_id INTEGER REFERENCES instrument (instrument_id),
    currency        TEXT NOT NULL DEFAULT 'USD',
    note            TEXT,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL,
    CHECK (closed_date IS NULL OR closed_date >= opened_date),
    CHECK (status = 'open' OR closed_date IS NOT NULL)
);

-- @table tax_rate_schedule
-- Effective-dated tax rates per account, stored as separate federal, state and
-- NIIT components so that the effective rate is explainable rather than a
-- magic number (bootstrap §4.2).
--
-- Effective-dated for the same reason `return_policy` is: a rate change must
-- not retroactively restate what last year's sale cost.
CREATE TABLE IF NOT EXISTS tax_rate_schedule (
    rate_id         INTEGER PRIMARY KEY,
    account_id      INTEGER NOT NULL REFERENCES account (account_id),
    effective_from  TEXT NOT NULL,
    -- Decimal fractions: 37% is '0.37'.
    short_term_federal TEXT NOT NULL,  -- decimal
    long_term_federal  TEXT NOT NULL,  -- decimal
    state              TEXT NOT NULL DEFAULT '0',  -- decimal
    niit               TEXT NOT NULL DEFAULT '0',  -- decimal
    -- Rate applied to qualified dividends, where it differs from long-term.
    qualified_dividend TEXT,  -- decimal
    note            TEXT,
    created_at      TEXT NOT NULL,
    UNIQUE (account_id, effective_from)
);

-- @table benchmark
-- A benchmark series. PORT-GIPS-G01: price-only benchmarks are prohibited in
-- performance reports, and `portable` refuses rather than warns.
CREATE TABLE IF NOT EXISTS benchmark (
    benchmark_id    INTEGER PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    description     TEXT NOT NULL,
    -- NOT NULL with NO DEFAULT, deliberately (PORT-GIPS-G01). A defaulted
    -- return_type is how a price-only series gets used by accident, and the
    -- S&P 500 price index is far easier to obtain than its total-return
    -- counterpart while understating the benchmark by roughly the dividend
    -- yield every year -- flattering the portfolio by 1.5-2% annually.
    return_type     TEXT NOT NULL CHECK (return_type IN ('total_return', 'price_only')),
    -- Disclosed when benchmark returns are calculated less frequently than
    -- monthly (PORT-GIPS-G05).
    periodicity     TEXT NOT NULL DEFAULT 'daily'
        CHECK (periodicity IN ('daily', 'weekly', 'monthly', 'quarterly', 'annual')),
    -- Whether the series is net of withholding taxes, where known
    -- (PORT-GIPS-G05). NULL means "not available", which is itself disclosed.
    is_net_of_withholding INTEGER CHECK (is_net_of_withholding IN (0, 1)),
    -- For a blend: how components are rebalanced. An explicit rule, not a
    -- config string (PORT-GIPS-G03). e.g. 'monthly', 'quarterly', 'none',
    -- 'drift_band:5'.
    rebalance_rule  TEXT,
    is_blend        INTEGER NOT NULL DEFAULT 0 CHECK (is_blend IN (0, 1)),
    source          TEXT NOT NULL DEFAULT 'manual',
    created_at      TEXT NOT NULL,
    CHECK (is_blend = 0 OR rebalance_rule IS NOT NULL)
);

-- @table benchmark_component
-- Components of a blended policy benchmark, with effective-dated weights
-- (PORT-GIPS-G03). A blend is a stored object, not a formula in a config
-- string, because its composition must be disclosed as of each annual period
-- end.
CREATE TABLE IF NOT EXISTS benchmark_component (
    component_id    INTEGER PRIMARY KEY,
    benchmark_id    INTEGER NOT NULL REFERENCES benchmark (benchmark_id),
    -- Exactly one of these is set.
    component_benchmark_id INTEGER REFERENCES benchmark (benchmark_id),
    component_instrument_id INTEGER REFERENCES instrument (instrument_id),
    weight          TEXT NOT NULL,  -- decimal
    effective_from  TEXT NOT NULL,
    label           TEXT,
    CHECK (
        (component_benchmark_id IS NOT NULL AND component_instrument_id IS NULL)
        OR (component_benchmark_id IS NULL AND component_instrument_id IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_benchmark_component
    ON benchmark_component (benchmark_id, effective_from);

-- @table benchmark_level
-- Observed benchmark index levels or period returns. Kept separate from
-- `price` because a benchmark is not an instrument and must not accidentally
-- be valued as one.
CREATE TABLE IF NOT EXISTS benchmark_level (
    benchmark_id    INTEGER NOT NULL REFERENCES benchmark (benchmark_id),
    level_date      TEXT NOT NULL,
    -- Index level. Total-return series only, per PORT-GIPS-G01.
    level           TEXT NOT NULL,  -- decimal
    source          TEXT NOT NULL,
    as_of           TEXT NOT NULL,
    PRIMARY KEY (benchmark_id, level_date)
);

-- @table portfolio_benchmark
-- Which benchmark applies to the portfolio, effective-dated, with the reason
-- for every change (PORT-GIPS-G04: disclose the date and description of any
-- benchmark change; prospective changes are disclosed for as long as returns
-- for the prior benchmark remain in the report).
CREATE TABLE IF NOT EXISTS portfolio_benchmark (
    id              INTEGER PRIMARY KEY,
    benchmark_id    INTEGER NOT NULL REFERENCES benchmark (benchmark_id),
    effective_from  TEXT NOT NULL,
    change_type     TEXT NOT NULL CHECK (change_type IN ('prospective', 'retroactive')),
    change_reason   TEXT NOT NULL,
    created_at      TEXT NOT NULL,
    UNIQUE (effective_from, benchmark_id)
);

-- @table return_policy
-- Effective-dated thresholds that GIPS requires an entity to define and
-- supplies no number for (PORT-GIPS-B03, E09, J01).
--
-- These are NOT configuration. They live in the .port file because they must
-- be reconstructible for historical periods: a threshold that lived in
-- ~/.portablerc could not be recovered for a period that ended two years ago.
-- Effective-dated for the same reason tax rates are.
--
-- A missing policy is an ERROR, not a zero (PT-E-GIPS-NO-FLOW-POLICY).
CREATE TABLE IF NOT EXISTS return_policy (
    policy_id       INTEGER PRIMARY KEY,
    effective_from  TEXT NOT NULL UNIQUE,
    -- LARGE cash flow: the level at which a flow may distort the return if the
    -- portfolio is not valued and a sub-period return calculated. Triggers
    -- revaluation. GIPS glossary; the amount must be defined by the asset
    -- owner in currency or as a percentage of assets.
    large_flow_basis TEXT NOT NULL CHECK (large_flow_basis IN ('amount', 'percent')),
    large_flow_value TEXT NOT NULL,  -- decimal
    -- SIGNIFICANT cash flow: a DIFFERENT threshold for a DIFFERENT purpose --
    -- temporary removal of a portfolio from a composite. A flow can be one
    -- without being the other, so these are separate fields and not one
    -- (PORT-GIPS-E09). NULL until composites exist (v1.0).
    significant_flow_basis TEXT
        CHECK (significant_flow_basis IS NULL OR significant_flow_basis IN ('amount', 'percent')),
    significant_flow_value TEXT,  -- decimal
    -- Materiality for error correction. GIPS supplies no number here either
    -- (PORT-GIPS-J01): the entity defines it. Two thresholds, whichever binds
    -- first.
    materiality_return_bps TEXT,  -- decimal
    materiality_value      TEXT,  -- decimal
    -- Which return basis feeds the risk measures. GIPS recommends
    -- gross-of-fees and requires the choice be disclosed (PORT-GIPS-F04).
    risk_measure_basis TEXT NOT NULL DEFAULT 'gross_of_fees'
        CHECK (risk_measure_basis IN
            ('gross_of_fees', 'net_of_external_costs_only', 'net_of_fees')),
    note            TEXT,
    created_at      TEXT NOT NULL,
    CHECK ((significant_flow_basis IS NULL) = (significant_flow_value IS NULL))
);

-- @table portfolio_event
-- Significant events that help a reader interpret a report (PORT-GIPS-I08 /
-- AO 24.C.16). Disclosed for a minimum of one year and as long as relevant --
-- `expiry_date` carries that, so the disclosure engine can drop it on
-- schedule rather than relying on somebody remembering.
CREATE TABLE IF NOT EXISTS portfolio_event (
    event_id        INTEGER PRIMARY KEY,
    event_date      TEXT NOT NULL,
    description     TEXT NOT NULL,
    -- NULL means "no expiry set"; the engine then applies the one-year floor.
    expiry_date     TEXT,
    created_at      TEXT NOT NULL
);

-- @table report_issue
-- Issued reports, for error detection and correction (PORT-GIPS-J01, J02).
--
-- The content hash is what makes this cheap and exact, and `portable`'s
-- determinism guarantee is what makes the hash meaningful (PORT-GIPS-J06):
-- rebuild a report, hash it, compare. A correction is a NEW issue referencing
-- the superseded one -- the same discipline the ledger imposes on
-- transactions, extended to reports.
CREATE TABLE IF NOT EXISTS report_issue (
    report_issue_id INTEGER PRIMARY KEY,
    -- Stable identity of the report, e.g. 'annual:2025' or 'tax:2025'.
    report_id       TEXT NOT NULL,
    issued_at       TEXT NOT NULL,
    -- SHA-256 of the canonical JSON output.
    content_hash    TEXT NOT NULL,
    command         TEXT NOT NULL,
    params_json     TEXT NOT NULL,
    -- Set on the OLD row when a corrected issue replaces it. Never deleted.
    superseded_by   INTEGER REFERENCES report_issue (report_issue_id),
    -- Why it was superseded, and whether the difference was material.
    correction_reason TEXT,
    is_material     INTEGER CHECK (is_material IN (0, 1)),
    created_at      TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_report_issue_report ON report_issue (report_id, issued_at);

-- @table settings
-- Portfolio-scoped settings. Distinct from `meta` (identity) and from
-- `return_policy` (effective-dated methodology), and distinct again from
-- ~/.portablerc, which is user-scoped and not part of the portfolio.
CREATE TABLE IF NOT EXISTS settings (
    key             TEXT PRIMARY KEY,
    value           TEXT NOT NULL,
    updated_at      TEXT NOT NULL
);

-- =============================================================================
-- LEDGER -- append-only, the source of truth
-- =============================================================================

-- @table transaction
-- The immutable ledger. Everything else about the portfolio is derived from
-- these rows (ADR 0010).
--
-- UPDATE and DELETE are rejected by trigger. A mistake is corrected with a
-- reversing entry plus a new entry, never by editing history -- that is what
-- makes the tax trail defensible and what makes `--as-of` time travel mean
-- something.
--
-- Replay order is (trade_date, seq, txn_id). NOT created_at: a wall clock is
-- not a total order across machines and CLAUDE.md invariant 6 forbids
-- depending on one. NOT trade_date alone: two trades on one day in the wrong
-- order consume the wrong lots under FIFO.
CREATE TABLE IF NOT EXISTS "transaction" (
    txn_id          INTEGER PRIMARY KEY,
    account_id      INTEGER NOT NULL REFERENCES account (account_id),
    -- Recognition is on trade date (PORT-GIPS-A05). Settlement is recorded but
    -- does not drive position or P&L recognition. This is stricter than the
    -- archived T+3 accommodation, whose Q&A lapsed on 2019-12-31.
    trade_date      TEXT NOT NULL,
    settlement_date TEXT,
    -- Sequence within the trade date, assigned at insert from the ledger's
    -- existing maximum. Gives the ledger a total order that does not depend on
    -- a clock.
    seq             INTEGER NOT NULL,
    txn_type        TEXT NOT NULL CHECK (txn_type IN (
        -- trades
        'buy', 'sell', 'sell_short', 'buy_to_cover',
        -- cash
        'deposit', 'withdrawal', 'transfer', 'journal',
        'interest', 'fee', 'margin_interest',
        -- income
        'dividend', 'dividend_reinvest', 'return_of_capital', 'coupon',
        'accrual_income',
        -- corporate actions
        'split', 'reverse_split', 'stock_dividend', 'spinoff',
        'merger_cash', 'merger_stock', 'merger_mixed', 'symbol_change', 'delist',
        -- options lifecycle
        'option_exercise', 'option_assignment', 'option_expiration',
        -- fixed income lifecycle
        'bond_amortization', 'bond_accretion', 'bond_call', 'bond_maturity',
        -- adjustments
        'reversal', 'correction'
    )),
    instrument_id   INTEGER REFERENCES instrument (instrument_id),
    quantity        TEXT,  -- decimal
    price           TEXT,  -- decimal
    gross_amount    TEXT,  -- decimal
    -- Always canonical 2dp, so that '0.00' is an exact test for "no fee" and
    -- the fee_class CHECK below can bind without numeric comparison in SQL.
    fees            TEXT NOT NULL DEFAULT '0.00',  -- decimal
    commissions     TEXT NOT NULL DEFAULT '0.00',  -- decimal
    taxes_withheld  TEXT NOT NULL DEFAULT '0.00',  -- decimal
    -- Reclaimable withholding is accrued; non-reclaimable reduces return
    -- (PORT-GIPS-A06 / Firms 2.B.5). Splitting them is the only way to get
    -- both right.
    withholding_reclaimable TEXT,  -- decimal
    -- The three return bases are DERIVED from this (PORT-GIPS-D01). NULL where
    -- a fee is present must be an error, not a silent default -- the CHECK
    -- below is what makes that true for every writer, including `pt import`
    -- and any future broker adapter.
    --
    -- Note that under the Asset Owner ladder `portable` follows, a custody fee
    -- is an internal_mgmt_cost and reduces net-of-fees only. It is NOT a
    -- transaction_cost, in either regime.
    fee_class       TEXT CHECK (fee_class IN (
        'transaction_cost', 'embedded_fund_fee', 'external_mgmt_fee',
        'internal_mgmt_cost', 'other_admin'
    )),
    -- Signed effect on the account's cash balance.
    net_cash_effect TEXT NOT NULL,  -- decimal
    position_id     INTEGER,
    -- For a transfer: the other side. ONE transaction, not two, so that
    -- portfolio-level netting is structural rather than a matching heuristic
    -- (ADR 0007). At portfolio level a transfer yields NO flow -- not two
    -- flows that happen to cancel, which would still break a sub-period.
    counter_account_id INTEGER REFERENCES account (account_id),
    -- Links a roll's close to its open, an assignment to its stock leg, a
    -- spinoff's parent to its child.
    related_txn_id  INTEGER REFERENCES "transaction" (txn_id),
    -- Set on a reversal, pointing at what it reverses.
    reverses_txn_id INTEGER REFERENCES "transaction" (txn_id),
    -- Explicit lot designation for spec-ID, as 'lot_id:qty;lot_id:qty'.
    lot_selection   TEXT,
    relief_method   TEXT CHECK (relief_method IN
        ('spec', 'fifo', 'lifo', 'hifo', 'lofo', 'avg')),
    -- Income dates. Entitlement on ex_date, cash on pay_date.
    ex_date         TEXT,
    pay_date        TEXT,
    -- Qualified dividend flag; NULL where not applicable.
    is_qualified    INTEGER CHECK (is_qualified IN (0, 1)),
    note            TEXT,
    -- The broker confirm id. Used for duplicate detection on import.
    external_ref    TEXT,
    source          TEXT NOT NULL DEFAULT 'manual'
        CHECK (source IN ('manual', 'import', 'derived')),
    -- Wall-clock provenance. Recorded, but NEVER used for ordering.
    created_at      TEXT NOT NULL,
    UNIQUE (trade_date, seq),
    -- PORT-GIPS-D01: a fee with no classification is refused, not guessed.
    CHECK (
        (fees = '0.00' AND commissions = '0.00')
        OR fee_class IS NOT NULL
    ),
    -- A transfer needs somewhere to transfer to; nothing else may have one.
    CHECK (
        (txn_type = 'transfer' AND counter_account_id IS NOT NULL)
        OR (txn_type <> 'transfer' AND counter_account_id IS NULL)
    ),
    CHECK ((txn_type = 'reversal') = (reverses_txn_id IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS ix_txn_account_date ON "transaction" (account_id, trade_date);
CREATE INDEX IF NOT EXISTS ix_txn_instrument_date ON "transaction" (instrument_id, trade_date);
CREATE INDEX IF NOT EXISTS ix_txn_position ON "transaction" (position_id);
CREATE INDEX IF NOT EXISTS ix_txn_type_date ON "transaction" (txn_type, trade_date);
CREATE INDEX IF NOT EXISTS ix_txn_order ON "transaction" (trade_date, seq);
CREATE INDEX IF NOT EXISTS ix_txn_external_ref
    ON "transaction" (external_ref) WHERE external_ref IS NOT NULL;

-- CLAUDE.md invariant 2, enforced by the database rather than by convention.
-- These triggers are the reason the audit trail is defensible: no code path,
-- including a future one nobody has written yet, can edit history.
CREATE TRIGGER IF NOT EXISTS trg_transaction_no_update
BEFORE UPDATE ON "transaction"
BEGIN
    -- RAISE() takes a string literal, so this cannot be wrapped. The
    -- fuller explanation is on PT-E-LEDGER-IMMUTABLE at the CLI boundary.
    SELECT RAISE(ABORT, 'PT-E-LEDGER-IMMUTABLE: the ledger is append-only; correct with a reversing entry (pt trade reverse), never by editing history');
END;

CREATE TRIGGER IF NOT EXISTS trg_transaction_no_delete
BEFORE DELETE ON "transaction"
BEGIN
    -- RAISE() takes a string literal, so this cannot be wrapped. The
    -- fuller explanation is on PT-E-LEDGER-IMMUTABLE at the CLI boundary.
    SELECT RAISE(ABORT, 'PT-E-LEDGER-IMMUTABLE: the ledger is append-only; correct with a reversing entry (pt trade reverse), never by deleting history');
END;

-- =============================================================================
-- DERIVED -- dropped and rebuilt by `pt rebuild`
-- =============================================================================

-- @table position
-- The container, and the unit of trader intent. A position MAY SPAN MULTIPLE
-- INSTRUMENTS: a covered call is one position, not two (ADR 0009).
CREATE TABLE IF NOT EXISTS position (
    position_id     INTEGER PRIMARY KEY,
    account_id      INTEGER NOT NULL REFERENCES account (account_id),
    strategy_type   TEXT NOT NULL DEFAULT 'single'
        CHECK (strategy_type IN (
            'single', 'covered_call', 'vertical', 'calendar', 'diagonal',
            'collar', 'straddle', 'strangle', 'custom'
        )),
    opened_date     TEXT NOT NULL,
    closed_date     TEXT,
    status          TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    label           TEXT,
    note            TEXT,
    -- The transaction that opened it, so replay can reproduce identity.
    opened_txn_id   INTEGER REFERENCES "transaction" (txn_id),
    CHECK (status = 'open' OR closed_date IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS ix_position_account_status ON position (account_id, status);

-- @table position_leg
-- Binds one instrument to a position with a role and a sign. The role is what
-- lets the engines know that *this* short call is written against *that*
-- stock, which is what makes assignment a within-position operation rather
-- than a cross-position fixup (ADR 0009).
CREATE TABLE IF NOT EXISTS position_leg (
    leg_id          INTEGER PRIMARY KEY,
    position_id     INTEGER NOT NULL REFERENCES position (position_id),
    instrument_id   INTEGER NOT NULL REFERENCES instrument (instrument_id),
    role            TEXT NOT NULL CHECK (role IN (
        'underlying', 'long_call', 'short_call', 'long_put', 'short_put',
        'long_stock', 'short_stock', 'bond', 'hedge', 'other'
    )),
    -- +1 long, -1 short.
    sign            INTEGER NOT NULL CHECK (sign IN (-1, 1)),
    -- Materialized from the leg's open lots. The per-leg form of CLAUDE.md
    -- invariant 5: sum(lot.remaining_quantity) == leg.quantity. Per LEG, not
    -- per position -- a position spanning two instruments has no scalar
    -- quantity, so stating the invariant per position would be meaningless
    -- for exactly the case the model exists for (ADR 0009).
    quantity        TEXT NOT NULL DEFAULT '0',  -- decimal
    opened_date     TEXT NOT NULL,
    closed_date     TEXT,
    status          TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    UNIQUE (position_id, instrument_id, role)
);

CREATE INDEX IF NOT EXISTS ix_leg_position ON position_leg (position_id);
CREATE INDEX IF NOT EXISTS ix_leg_instrument ON position_leg (instrument_id, status);

-- @table lot
-- Created by an opening transaction, consumed by closing ones. Lots are the
-- tax engine's atoms. A lot hangs off a LEG, not off a position, because a lot
-- must resolve to exactly one instrument and a position need not.
CREATE TABLE IF NOT EXISTS lot (
    lot_id          INTEGER PRIMARY KEY,
    leg_id          INTEGER NOT NULL REFERENCES position_leg (leg_id),
    position_id     INTEGER NOT NULL REFERENCES position (position_id),
    -- Denormalised for the queries the LotEngine actually runs.
    instrument_id   INTEGER NOT NULL REFERENCES instrument (instrument_id),
    account_id      INTEGER NOT NULL REFERENCES account (account_id),
    open_date       TEXT NOT NULL,
    open_txn_id     INTEGER NOT NULL REFERENCES "transaction" (txn_id),
    original_quantity  TEXT NOT NULL,  -- decimal
    remaining_quantity TEXT NOT NULL,  -- decimal
    per_unit_price     TEXT NOT NULL,  -- decimal
    allocated_fees     TEXT NOT NULL DEFAULT '0.00',  -- decimal
    -- Basis as originally established, before adjustments. Kept so that the
    -- adjustment log can be checked against it.
    original_cost_basis TEXT NOT NULL,  -- decimal
    -- Basis as it now stands. Every change is explained by a row in
    -- lot_basis_adjustment.
    adjusted_cost_basis TEXT NOT NULL,  -- decimal
    -- Long-term requires MORE THAN ONE YEAR measured from the DAY AFTER
    -- acquisition. A split does not reset this; a spinoff's new shares inherit
    -- it. Wash sales (v0.2) will move it.
    holding_period_start TEXT NOT NULL,
    -- Short sales are always short-term regardless of holding period.
    is_short        INTEGER NOT NULL DEFAULT 0 CHECK (is_short IN (0, 1)),
    status          TEXT NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'partial', 'closed')),
    closed_date     TEXT,
    CHECK (status <> 'closed' OR closed_date IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS ix_lot_leg ON lot (leg_id, status);
CREATE INDEX IF NOT EXISTS ix_lot_instrument_account
    ON lot (instrument_id, account_id, status);
CREATE INDEX IF NOT EXISTS ix_lot_open_date ON lot (open_date);

-- @table lot_basis_adjustment
-- Every change to a lot's basis or holding-period start, with its reason. This
-- log is the difference between a basis you can defend and one you can only
-- assert.
CREATE TABLE IF NOT EXISTS lot_basis_adjustment (
    adjustment_id   INTEGER PRIMARY KEY,
    lot_id          INTEGER NOT NULL REFERENCES lot (lot_id),
    adjustment_date TEXT NOT NULL,
    reason          TEXT NOT NULL CHECK (reason IN (
        'commission', 'fee', 'return_of_capital', 'split', 'reverse_split',
        'stock_dividend', 'spinoff', 'merger', 'option_premium_exercise',
        'option_premium_assignment', 'amortization', 'accretion',
        'wash_sale', 'manual_correction', 'forced_zero_basis'
    )),
    -- Signed change to adjusted_cost_basis.
    basis_delta     TEXT NOT NULL DEFAULT '0.00',  -- decimal
    -- Signed change to quantity (a split multiplies; this records the delta).
    quantity_delta  TEXT NOT NULL DEFAULT '0',  -- decimal
    -- The holding-period start after this adjustment. A split leaves it
    -- unchanged; recording it explicitly makes that assertion checkable rather
    -- than implicit.
    holding_period_start_after TEXT NOT NULL,
    txn_id          INTEGER REFERENCES "transaction" (txn_id),
    note            TEXT
);

CREATE INDEX IF NOT EXISTS ix_basis_adjustment_lot ON lot_basis_adjustment (lot_id);

-- @table lot_disposition
-- One row per (closing transaction, lot consumed). The tax engine's input.
CREATE TABLE IF NOT EXISTS lot_disposition (
    disposition_id  INTEGER PRIMARY KEY,
    lot_id          INTEGER NOT NULL REFERENCES lot (lot_id),
    txn_id          INTEGER NOT NULL REFERENCES "transaction" (txn_id),
    account_id      INTEGER NOT NULL REFERENCES account (account_id),
    instrument_id   INTEGER NOT NULL REFERENCES instrument (instrument_id),
    disposition_date TEXT NOT NULL,
    quantity        TEXT NOT NULL,  -- decimal
    -- Includes option premium where an assignment resolved into stock: a
    -- written call that is assigned adds its premium to PROCEEDS, not to
    -- independent P&L.
    proceeds        TEXT NOT NULL,  -- decimal
    allocated_fees  TEXT NOT NULL DEFAULT '0.00',  -- decimal
    cost_basis_relieved TEXT NOT NULL,  -- decimal
    realized_gain   TEXT NOT NULL,  -- decimal
    -- Determined at disposition from the lot's holding_period_start. Short
    -- sales are always 'short'.
    holding_period  TEXT NOT NULL CHECK (holding_period IN ('short', 'long')),
    -- Days held, recorded so the boundary determination is auditable rather
    -- than having to be recomputed to be checked.
    days_held       INTEGER NOT NULL,
    relief_method   TEXT NOT NULL
        CHECK (relief_method IN ('spec', 'fifo', 'lifo', 'hifo', 'lofo', 'avg')),
    -- v0.2. Until wash-sale detection lands this is always NULL and the tax
    -- report says on its face that it does not account for wash sales.
    wash_sale_deferred TEXT  -- decimal
);

CREATE INDEX IF NOT EXISTS ix_disposition_txn ON lot_disposition (txn_id);
CREATE INDEX IF NOT EXISTS ix_disposition_account_date
    ON lot_disposition (account_id, disposition_date);
CREATE INDEX IF NOT EXISTS ix_disposition_lot ON lot_disposition (lot_id);

-- @table realized_gain
-- Per-disposition realized gain with the estimated tax applied, materialized
-- for `pt tax` and `pt pnl --net-of-tax`.
--
-- The tax figure is an ESTIMATE: gain times the account's effective-dated rate
-- for the holding period at disposition. It does not model brackets, the
-- capital-loss limitation, carryforwards, rate stacking, AMT, or any other
-- income (ADR 0011). The components are stored separately so the effective
-- rate is explainable rather than a magic number.
CREATE TABLE IF NOT EXISTS realized_gain (
    realized_gain_id INTEGER PRIMARY KEY,
    disposition_id  INTEGER NOT NULL UNIQUE REFERENCES lot_disposition (disposition_id),
    account_id      INTEGER NOT NULL REFERENCES account (account_id),
    instrument_id   INTEGER NOT NULL REFERENCES instrument (instrument_id),
    tax_year        INTEGER NOT NULL,
    disposition_date TEXT NOT NULL,
    holding_period  TEXT NOT NULL CHECK (holding_period IN ('short', 'long')),
    proceeds        TEXT NOT NULL,  -- decimal
    cost_basis      TEXT NOT NULL,  -- decimal
    gain            TEXT NOT NULL,  -- decimal
    -- The rate schedule row used, so the estimate can be traced.
    rate_id         INTEGER REFERENCES tax_rate_schedule (rate_id),
    federal_rate    TEXT,  -- decimal
    state_rate      TEXT,  -- decimal
    niit_rate       TEXT,  -- decimal
    estimated_tax   TEXT,  -- decimal
    -- 0 for tax_deferred and tax_exempt accounts, where the estimate is not
    -- merely zero but inapplicable; the flag says which.
    is_taxable      INTEGER NOT NULL CHECK (is_taxable IN (0, 1))
);

CREATE INDEX IF NOT EXISTS ix_realized_gain_year
    ON realized_gain (tax_year, account_id);

-- @table cash_balance
-- Current cash and margin per account and currency. Derived: the authoritative
-- history is the ledger, and a balance at any past date is obtained by replay
-- or from a valuation snapshot.
CREATE TABLE IF NOT EXISTS cash_balance (
    account_id      INTEGER NOT NULL REFERENCES account (account_id),
    currency        TEXT NOT NULL DEFAULT 'USD',
    balance         TEXT NOT NULL DEFAULT '0.00',  -- decimal
    -- A modelled liability, not a memo (PORT-GIPS-D04). Market value is assets
    -- MINUS this; returns are net of discretionary leverage and are not
    -- grossed up as if it did not exist.
    margin_loan     TEXT NOT NULL DEFAULT '0.00',  -- decimal
    -- The ledger position this balance reflects, for replay verification.
    last_txn_id     INTEGER REFERENCES "transaction" (txn_id),
    PRIMARY KEY (account_id, currency)
);

-- @table valuation_snapshot
-- Per account per date: the substrate `pert` needs (bootstrap §4.7).
--
-- `portable` values DAILY where prices exist. That satisfies the GIPS monthly
-- floor and the month-end requirement (PORT-GIPS-A03), satisfies the
-- recommendation to value on every external cash flow date, and removes the
-- need for any within-period approximation (PORT-GIPS-B06).
CREATE TABLE IF NOT EXISTS valuation_snapshot (
    snapshot_id     INTEGER PRIMARY KEY,
    account_id      INTEGER NOT NULL REFERENCES account (account_id),
    snapshot_date   TEXT NOT NULL,
    beginning_market_value TEXT NOT NULL,  -- decimal
    ending_market_value    TEXT NOT NULL,  -- decimal
    -- Ending market value is securities + cash - margin_loan + accrued income.
    securities_value TEXT NOT NULL,  -- decimal
    cash_balance    TEXT NOT NULL,  -- decimal
    margin_loan     TEXT NOT NULL DEFAULT '0.00',  -- decimal
    -- Accrued income is part of beginning and ending value, not a memo
    -- (PORT-GIPS-A06). Accrual is REQUIRED for interest-bearing instruments
    -- and RECOMMENDED for dividends; `portable` does both but must not
    -- describe the dividend half as required.
    accrued_interest TEXT NOT NULL DEFAULT '0.00',  -- decimal
    accrued_dividends TEXT NOT NULL DEFAULT '0.00',  -- decimal
    -- Sum of the two, materialized for the return path.
    accrued_income  TEXT NOT NULL DEFAULT '0.00',  -- decimal
    -- External cash flow at ACCOUNT level, on this date. Income is never here.
    external_flow_account TEXT NOT NULL DEFAULT '0.00',  -- decimal
    -- External cash flow at PORTFOLIO level. An inter-account transfer nets to
    -- zero here and yields NO flow at all -- see ADR 0007 and PORT-GIPS-B02.
    external_flow_portfolio TEXT NOT NULL DEFAULT '0.00',  -- decimal
    income_amount   TEXT NOT NULL DEFAULT '0.00',  -- decimal
    fees_amount     TEXT NOT NULL DEFAULT '0.00',  -- decimal
    -- Market value priced at hierarchy level 5 (subjective, unobservable
    -- inputs), for PORT-GIPS-H05. Zero for a listed portfolio -- rendered
    -- anyway, because "0%" is information and a missing row is not.
    level5_market_value TEXT NOT NULL DEFAULT '0.00',  -- decimal
    -- 0 when any position could not be priced. A snapshot that is not complete
    -- must not be silently used for a return.
    is_complete     INTEGER NOT NULL DEFAULT 1 CHECK (is_complete IN (0, 1)),
    -- 1 when any consumed price was flagged an estimate (PORT-GIPS-A09/I10).
    uses_estimates  INTEGER NOT NULL DEFAULT 0 CHECK (uses_estimates IN (0, 1)),
    UNIQUE (account_id, snapshot_date)
);

CREATE INDEX IF NOT EXISTS ix_snapshot_date ON valuation_snapshot (snapshot_date);

-- @table valuation_snapshot_price
-- The exact set of prices a snapshot consumed. This is what PORT-GIPS-J03
-- requires -- supporting data for every reported figure -- and what makes
-- PORT-GIPS-A09 workable: when a better price arrives, the snapshots that used
-- the estimate are identifiable and can be rebuilt.
CREATE TABLE IF NOT EXISTS valuation_snapshot_price (
    snapshot_id     INTEGER NOT NULL REFERENCES valuation_snapshot (snapshot_id),
    instrument_id   INTEGER NOT NULL REFERENCES instrument (instrument_id),
    price_id        INTEGER REFERENCES price (price_id),
    price           TEXT NOT NULL,  -- decimal
    quantity        TEXT NOT NULL,  -- decimal
    market_value    TEXT NOT NULL,  -- decimal
    source          TEXT NOT NULL,
    as_of           TEXT NOT NULL,
    valuation_level INTEGER NOT NULL CHECK (valuation_level BETWEEN 1 AND 5),
    is_estimate     INTEGER NOT NULL DEFAULT 0 CHECK (is_estimate IN (0, 1)),
    -- Days between price_date and snapshot_date. Zero on a normal day; a
    -- positive number is a stale price, permitted only within tolerance and
    -- only when flagged (PORT-GIPS-A09).
    staleness_days  INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (snapshot_id, instrument_id)
);

-- @table snapshot_flow
-- Individual external cash flows with DAY resolution, which is what the
-- money-weighted return requires (PORT-GIPS-C02 / Firms 2.A.29: daily external
-- cash flows for periods beginning on or after 1 January 2020).
--
-- The `level` column is the whole point: the same transaction can be an
-- external flow at account level and not one at portfolio level. The
-- classification comes from ONE service function and is never re-derived at a
-- call site (ADR 0007).
CREATE TABLE IF NOT EXISTS snapshot_flow (
    flow_id         INTEGER PRIMARY KEY,
    snapshot_id     INTEGER NOT NULL REFERENCES valuation_snapshot (snapshot_id),
    txn_id          INTEGER NOT NULL REFERENCES "transaction" (txn_id),
    account_id      INTEGER NOT NULL REFERENCES account (account_id),
    flow_date       TEXT NOT NULL,
    level           TEXT NOT NULL CHECK (level IN ('account', 'portfolio')),
    classification  TEXT NOT NULL
        CHECK (classification IN ('external', 'internal', 'income', 'cost')),
    -- Signed: positive into the portfolio, negative out.
    amount          TEXT NOT NULL,  -- decimal
    -- 1 when this flow exceeded the large-flow threshold in force on its date,
    -- which under PORT-GIPS-B03 would require revaluation and a sub-period
    -- return were daily returns not being computed.
    is_large        INTEGER NOT NULL DEFAULT 0 CHECK (is_large IN (0, 1)),
    -- In-kind transfers and stock distributions are flows valued at the time
    -- of distribution (PORT-GIPS-C02 / Firms 2.A.29.c).
    is_in_kind      INTEGER NOT NULL DEFAULT 0 CHECK (is_in_kind IN (0, 1))
);

CREATE INDEX IF NOT EXISTS ix_flow_date_level ON snapshot_flow (flow_date, level);
CREATE INDEX IF NOT EXISTS ix_flow_snapshot ON snapshot_flow (snapshot_id);
